// src/components/Block/Block.jsx
import React, {useState} from 'react';
import RenderContent from '../../utils/Render';

import './style.css'

const Block = ({ items }) => {
  const [show, setShow] = useState(0)

  return (
    <div>
      <div className="customBlock border-2 rounded-lg p-2 mb-2">
        {items.map((item, index) => (
          <div key={'bfr'+index} className={`item ${show==index ? '' : 'hidden'}`}>
            {item.content.map((contentItem, idx) => (
              <RenderContent key={'bsr'+idx} item={contentItem} />
            ))}
          </div>
        ))}
      </div>
      <div className='flex justify-center'>
        {/* <button onClick={ () => {setShow( show==0 ? items.length-1 : show-1 )}} > &lt; </button> */}
        {items.map( (item,index) => (
          <button key={'btn'+index} onClick={ () => {setShow( index )}} className={`${show==index ? 'bg-green-600' : ''} mx-2 w-12 h-12 block rounded-lg font-bold focus:outline-none`}> {index+1} </button>
        ))}
        {/* <button onClick={ () => {setShow( (show+1)%items.length )}} > &gt; </button> */}
      </div>
    </div>
  );
};

export default Block;

// src/components/book/Block.vue
<template>
  <div class="my-6">
    <div class="border-2 border-yellow-400 rounded-xl p-4 mb-3 min-h-[80px]">
      <div v-for="(item, index) in items" :key="'block-'+index" v-show="active === index">
        <RenderContent v-for="(c, i) in item.content" :key="'bc-'+i" :item="c" />
      </div>
    </div>
    <div class="flex justify-center gap-2">
      <button
        v-for="(_, index) in items"
        :key="'bbtn-'+index"
        @click="active = index"
        class="w-10 h-10 rounded-lg font-bold text-sm transition-colors"
        :class="active === index
          ? 'bg-yellow-400 text-gray-900'
          : 'bg-gray-100 hover:bg-yellow-200 text-gray-600'"
      >
        {{ index + 1 }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import RenderContent from './RenderContent.vue'

defineProps({
  items: { type: Array, required: true }
})

const active = ref(0)
</script>
